import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Annoucment from "@/components/Annoucment";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Klik Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Annoucment/>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
